name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login ECR
        run: |
          aws ecr get-login-password --region sa-east-1 \
          | docker login --username AWS --password-stdin 630968569878.dkr.ecr.sa-east-1.amazonaws.com

      - name: Build
        run: docker build -t dockerized-api .

      - name: Tag (version)
        run: |
          docker tag dockerized-api:latest 630968569878.dkr.ecr.sa-east-1.amazonaws.com/dockerized-api:${{ github.sha }}

      - name: Push
        run: |
          docker push 630968569878.dkr.ecr.sa-east-1.amazonaws.com/dockerized-api:${{ github.sha }}
      
      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --family dockerized-api-task \
            --network-mode awsvpc \
            --requires-compatibilities FARGATE \
            --cpu "256" \
            --memory "512" \
            --execution-role-arn arn:aws:iam::630968569878:role/ecsTaskExecutionRole \
            --container-definitions "[{
              \"name\": \"dockerized-api\",
              \"image\": \"630968569878.dkr.ecr.sa-east-1.amazonaws.com/dockerized-api:${{ github.sha }}\",
              \"portMappings\": [{\"containerPort\": 3000}],
              \"logConfiguration\": {
                \"logDriver\": \"awslogs\",
                \"options\": {
                  \"awslogs-group\": \"/ecs/dockerized-api\",
                  \"awslogs-region\": \"sa-east-1\",
                  \"awslogs-stream-prefix\": \"ecs\"

                }
              }
            }]"

      - name: Deploy STAGING
        run: |
          aws ecs update-service \
            --cluster dockerized-api-cluster \
            --service dockerized-api-service-staging \
            --task-definition dockerized-api-task \
            --force-new-deployment
  
  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production   # 🔥 esto activa aprobación manual

    steps:
      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy PROD
        run: |
          aws ecs update-service \
            --cluster dockerized-api-cluster \
            --service dockerized-api-task-service \
            --task-definition dockerized-api-task \
            --force-new-deployment